from pygame_widgets.constants import USEREVENT
PATH = "D:/Jáchym/Programování/Python/Pampuch"
SQUARE_SIZE = 32
STEP = 8  # must be a divider of SQUARE_SIZE
CHAR_WALL = '#'
CHAR_POINT = '.'
CHAR_EMPTY = ' '
CHAR_MONSTER = 'X'
CHAR_PAMPUCH = 'P'
FPS = 16
E_GAME_STARTED = USEREVENT
E_DEATH = USEREVENT + 1
E_GAME_FINISHED = USEREVENT + 2
INSPECTION = 2000
LIVES = 4
LABEL_RATIO = 9
QUEUE_SIZE = 4
