PATH = "D:/Jáchym/Programování/Python/Pampuch"
SQUARE_SIZE = 32
STEP = 8  # must be a divider of SQUARE_SIZE
CHAR_WALL = '#'
CHAR_POINT = '.'
CHAR_EMPTY = ' '
CHAR_MONSTER = 'X'
CHAR_PAMPUCH = 'P'
FPS = 20
